### ISSUE TITLE
Check Port Status

### ISSUE THREAD

**Issue by edenhazard701** [edenhazard701/Koena#2]

**Comment by edenhazard701** [comment]
How to check that the port 25 is opened for SMTP server?

**Comment by choace** [comment]
You can check the port status with fsockclose()- php function.

**Comment by edenhazard701** [comment]
The fsockopen() function is a standard cURL function and works with both PHP and Perl. It's not fit in this case.
What about getservbyport()?

**Comment by edenhazard701** [comment]
> The fsockopen() function is a standard cURL function and works with both PHP and Perl. It's not fit in this case. What about getservbyport()?
